services:
  mysql:
    image: mysql:8.0
    container_name: mysql-knowpals
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci

  redis:
    image: redis:latest
    container_name: redis-knowpals
    ports:
      - "6380:6379"
    command: redis-server --requirepass 12345678  # 设置密码
    restart: always
    volumes:
      - redis_data:/data


  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8889:8889"   # metrics给Prometheus抓

  prometheus:
    image: prom/prometheus:v3.5.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  tempo:
    image: grafana/tempo:2.8.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"

  grafana:
    image: grafana/grafana:12.1.0
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana-datasources-prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./grafana-datasources-tempo.yaml:/etc/grafana/provisioning/datasources/tempo.yaml
    ports:
      - "3000:3000"

volumes:
  mysql_data:
  redis_data:
