// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Knowpals/Knowpals-be-go/config"
	"github.com/Knowpals/Knowpals-be-go/controller"
	"github.com/Knowpals/Knowpals-be-go/infra/email"
	"github.com/Knowpals/Knowpals-be-go/ioc"
	"github.com/Knowpals/Knowpals-be-go/middleware"
	"github.com/Knowpals/Knowpals-be-go/pkg/ijwt"
	"github.com/Knowpals/Knowpals-be-go/repository/cache"
	"github.com/Knowpals/Knowpals-be-go/repository/dao"
	"github.com/Knowpals/Knowpals-be-go/service"
	"github.com/Knowpals/Knowpals-be-go/web"
)

// Injectors from wire.go:

func InitApp(conf *config.Config) *App {
	jwtHandler := ijwt.NewJwtHandler(conf)
	db := ioc.InitDB(conf)
	userDao := dao.NewUserDao(db)
	client := ioc.InitRedis(conf)
	emailClient := email.NewEmailClient(client, conf)
	authCache := cache.NewAuthCache(client)
	userService := service.NewUserService(userDao, emailClient, authCache)
	userController := controller.NewUserController(jwtHandler, userService)
	authMiddleware := middleware.NewAuthMiddleware(jwtHandler)
	logger := ioc.InitZapLogger(conf)
	loggerMiddleware := middleware.NewLoggerMiddleware(logger)
	engine := web.NewGinEngine(userController, authMiddleware, loggerMiddleware)
	app := NewApp(engine)
	return app
}
