// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	VideoId       string                 `protobuf:"bytes,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`             // optional
	KnowledgeId   string                 `protobuf:"bytes,4,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ChatRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *ChatRequest) GetKnowledgeId() string {
	if x != nil {
		return x.KnowledgeId
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	Context       string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	VideoId       string                 `protobuf:"bytes,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *ChatResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *ChatResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type GenerateQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	NumQuestions  int32                  `protobuf:"varint,3,opt,name=num_questions,json=numQuestions,proto3" json:"num_questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQuizRequest) Reset() {
	*x = GenerateQuizRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuizRequest) ProtoMessage() {}

func (x *GenerateQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuizRequest.ProtoReflect.Descriptor instead.
func (*GenerateQuizRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateQuizRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GenerateQuizRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *GenerateQuizRequest) GetNumQuestions() int32 {
	if x != nil {
		return x.NumQuestions
	}
	return 0
}

type QuizItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeId   string                 `protobuf:"bytes,1,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // choice|fill|judge
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	Answer        string                 `protobuf:"bytes,5,opt,name=answer,proto3" json:"answer,omitempty"`
	Analysis      string                 `protobuf:"bytes,6,opt,name=analysis,proto3" json:"analysis,omitempty"`
	Difficulty    string                 `protobuf:"bytes,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"` // easy|medium|hard
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizItem) Reset() {
	*x = QuizItem{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizItem) ProtoMessage() {}

func (x *QuizItem) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizItem.ProtoReflect.Descriptor instead.
func (*QuizItem) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *QuizItem) GetKnowledgeId() string {
	if x != nil {
		return x.KnowledgeId
	}
	return ""
}

func (x *QuizItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QuizItem) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *QuizItem) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *QuizItem) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *QuizItem) GetAnalysis() string {
	if x != nil {
		return x.Analysis
	}
	return ""
}

func (x *QuizItem) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

type GenerateQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quizzes       []*QuizItem            `protobuf:"bytes,1,rep,name=quizzes,proto3" json:"quizzes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQuizResponse) Reset() {
	*x = GenerateQuizResponse{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuizResponse) ProtoMessage() {}

func (x *GenerateQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuizResponse.ProtoReflect.Descriptor instead.
func (*GenerateQuizResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateQuizResponse) GetQuizzes() []*QuizItem {
	if x != nil {
		return x.Quizzes
	}
	return nil
}

type GenerateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportRequest) Reset() {
	*x = GenerateReportRequest{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportRequest) ProtoMessage() {}

func (x *GenerateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportRequest.ProtoReflect.Descriptor instead.
func (*GenerateReportRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateReportRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GenerateReportRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type ReportItem struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeId         string                 `protobuf:"bytes,1,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"`
	Mastery             float64                `protobuf:"fixed64,2,opt,name=mastery,proto3" json:"mastery,omitempty"`
	Summary             string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Weakness            []string               `protobuf:"bytes,4,rep,name=weakness,proto3" json:"weakness,omitempty"`
	BehaviorPattern     []string               `protobuf:"bytes,5,rep,name=behavior_pattern,json=behaviorPattern,proto3" json:"behavior_pattern,omitempty"`
	Trend               string                 `protobuf:"bytes,6,opt,name=trend,proto3" json:"trend,omitempty"`
	RecommendedSegments []*SegmentRef          `protobuf:"bytes,7,rep,name=recommended_segments,json=recommendedSegments,proto3" json:"recommended_segments,omitempty"` // jumpable refs
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReportItem) Reset() {
	*x = ReportItem{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportItem) ProtoMessage() {}

func (x *ReportItem) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportItem.ProtoReflect.Descriptor instead.
func (*ReportItem) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ReportItem) GetKnowledgeId() string {
	if x != nil {
		return x.KnowledgeId
	}
	return ""
}

func (x *ReportItem) GetMastery() float64 {
	if x != nil {
		return x.Mastery
	}
	return 0
}

func (x *ReportItem) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ReportItem) GetWeakness() []string {
	if x != nil {
		return x.Weakness
	}
	return nil
}

func (x *ReportItem) GetBehaviorPattern() []string {
	if x != nil {
		return x.BehaviorPattern
	}
	return nil
}

func (x *ReportItem) GetTrend() string {
	if x != nil {
		return x.Trend
	}
	return ""
}

func (x *ReportItem) GetRecommendedSegments() []*SegmentRef {
	if x != nil {
		return x.RecommendedSegments
	}
	return nil
}

type SegmentRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	SegmentId     string                 `protobuf:"bytes,2,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	StartMs       int64                  `protobuf:"varint,3,opt,name=start_ms,json=startMs,proto3" json:"start_ms,omitempty"`
	EndMs         int64                  `protobuf:"varint,4,opt,name=end_ms,json=endMs,proto3" json:"end_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentRef) Reset() {
	*x = SegmentRef{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentRef) ProtoMessage() {}

func (x *SegmentRef) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentRef.ProtoReflect.Descriptor instead.
func (*SegmentRef) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SegmentRef) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *SegmentRef) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *SegmentRef) GetStartMs() int64 {
	if x != nil {
		return x.StartMs
	}
	return 0
}

func (x *SegmentRef) GetEndMs() int64 {
	if x != nil {
		return x.EndMs
	}
	return 0
}

type GenerateReportResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Items          []*ReportItem          `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	OverallSummary string                 `protobuf:"bytes,3,opt,name=overall_summary,json=overallSummary,proto3" json:"overall_summary,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateReportResponse) Reset() {
	*x = GenerateReportResponse{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportResponse) ProtoMessage() {}

func (x *GenerateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportResponse.ProtoReflect.Descriptor instead.
func (*GenerateReportResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateReportResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *GenerateReportResponse) GetItems() []*ReportItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GenerateReportResponse) GetOverallSummary() string {
	if x != nil {
		return x.OverallSummary
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"~\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\tR\avideoId\x12!\n" +
	"\fknowledge_id\x18\x04 \x01(\tR\vknowledgeId\"Y\n" +
	"\fChatResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\tR\avideoId\"t\n" +
	"\x13GenerateQuizRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\x12#\n" +
	"\rnum_questions\x18\x03 \x01(\x05R\fnumQuestions\"\xcb\x01\n" +
	"\bQuizItem\x12!\n" +
	"\fknowledge_id\x18\x01 \x01(\tR\vknowledgeId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\x12\x16\n" +
	"\x06answer\x18\x05 \x01(\tR\x06answer\x12\x1a\n" +
	"\banalysis\x18\x06 \x01(\tR\banalysis\x12\x1e\n" +
	"\n" +
	"difficulty\x18\a \x01(\tR\n" +
	"difficulty\"A\n" +
	"\x14GenerateQuizResponse\x12)\n" +
	"\aquizzes\x18\x01 \x03(\v2\x0f.agent.QuizItemR\aquizzes\"Q\n" +
	"\x15GenerateReportRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\"\x86\x02\n" +
	"\n" +
	"ReportItem\x12!\n" +
	"\fknowledge_id\x18\x01 \x01(\tR\vknowledgeId\x12\x18\n" +
	"\amastery\x18\x02 \x01(\x01R\amastery\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1a\n" +
	"\bweakness\x18\x04 \x03(\tR\bweakness\x12)\n" +
	"\x10behavior_pattern\x18\x05 \x03(\tR\x0fbehaviorPattern\x12\x14\n" +
	"\x05trend\x18\x06 \x01(\tR\x05trend\x12D\n" +
	"\x14recommended_segments\x18\a \x03(\v2\x11.agent.SegmentRefR\x13recommendedSegments\"x\n" +
	"\n" +
	"SegmentRef\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x02 \x01(\tR\tsegmentId\x12\x19\n" +
	"\bstart_ms\x18\x03 \x01(\x03R\astartMs\x12\x15\n" +
	"\x06end_ms\x18\x04 \x01(\x03R\x05endMs\"\x85\x01\n" +
	"\x16GenerateReportResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12'\n" +
	"\x05items\x18\x02 \x03(\v2\x11.agent.ReportItemR\x05items\x12'\n" +
	"\x0foverall_summary\x18\x03 \x01(\tR\x0eoverallSummary2\xd7\x01\n" +
	"\fAgentService\x12/\n" +
	"\x04Chat\x12\x12.agent.ChatRequest\x1a\x13.agent.ChatResponse\x12G\n" +
	"\fGenerateQuiz\x12\x1a.agent.GenerateQuizRequest\x1a\x1b.agent.GenerateQuizResponse\x12M\n" +
	"\x0eGenerateReport\x12\x1c.agent.GenerateReportRequest\x1a\x1d.agent.GenerateReportResponseB=Z;github.com/Knowpals/Knowpals-be-go/api/grpc/agentpb;agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_agent_proto_goTypes = []any{
	(*ChatRequest)(nil),            // 0: agent.ChatRequest
	(*ChatResponse)(nil),           // 1: agent.ChatResponse
	(*GenerateQuizRequest)(nil),    // 2: agent.GenerateQuizRequest
	(*QuizItem)(nil),               // 3: agent.QuizItem
	(*GenerateQuizResponse)(nil),   // 4: agent.GenerateQuizResponse
	(*GenerateReportRequest)(nil),  // 5: agent.GenerateReportRequest
	(*ReportItem)(nil),             // 6: agent.ReportItem
	(*SegmentRef)(nil),             // 7: agent.SegmentRef
	(*GenerateReportResponse)(nil), // 8: agent.GenerateReportResponse
}
var file_agent_proto_depIdxs = []int32{
	3, // 0: agent.GenerateQuizResponse.quizzes:type_name -> agent.QuizItem
	7, // 1: agent.ReportItem.recommended_segments:type_name -> agent.SegmentRef
	6, // 2: agent.GenerateReportResponse.items:type_name -> agent.ReportItem
	0, // 3: agent.AgentService.Chat:input_type -> agent.ChatRequest
	2, // 4: agent.AgentService.GenerateQuiz:input_type -> agent.GenerateQuizRequest
	5, // 5: agent.AgentService.GenerateReport:input_type -> agent.GenerateReportRequest
	1, // 6: agent.AgentService.Chat:output_type -> agent.ChatResponse
	4, // 7: agent.AgentService.GenerateQuiz:output_type -> agent.GenerateQuizResponse
	8, // 8: agent.AgentService.GenerateReport:output_type -> agent.GenerateReportResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
