// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: memorypb/memory.proto

package memorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_QUESTION EventType = 0
	EventType_PAUSE    EventType = 1
	EventType_REPLAY   EventType = 2
	EventType_CHAT     EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "QUESTION",
		1: "PAUSE",
		2: "REPLAY",
		3: "CHAT",
	}
	EventType_value = map[string]int32{
		"QUESTION": 0,
		"PAUSE":    1,
		"REPLAY":   2,
		"CHAT":     3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_memorypb_memory_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_memorypb_memory_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_memorypb_memory_proto_rawDescGZIP(), []int{0}
}

type Event struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	StudentId   string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	KnowledgeId string                 `protobuf:"bytes,2,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"`
	VideoId     string                 `protobuf:"bytes,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	SegmentId   string                 `protobuf:"bytes,4,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Ts          int64                  `protobuf:"varint,5,opt,name=ts,proto3" json:"ts,omitempty"`
	EventType   EventType              `protobuf:"varint,6,opt,name=event_type,json=eventType,proto3,enum=memory.EventType" json:"event_type,omitempty"`
	// Types that are valid to be assigned to Detail:
	//
	//	*Event_Question
	//	*Event_Chat
	Detail        isEvent_Detail `protobuf_oneof:"detail"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_memorypb_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_memorypb_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_memorypb_memory_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Event) GetKnowledgeId() string {
	if x != nil {
		return x.KnowledgeId
	}
	return ""
}

func (x *Event) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *Event) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *Event) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Event) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_QUESTION
}

func (x *Event) GetDetail() isEvent_Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *Event) GetQuestion() *QuestionEvent {
	if x != nil {
		if x, ok := x.Detail.(*Event_Question); ok {
			return x.Question
		}
	}
	return nil
}

func (x *Event) GetChat() *ChatEvent {
	if x != nil {
		if x, ok := x.Detail.(*Event_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

type isEvent_Detail interface {
	isEvent_Detail()
}

type Event_Question struct {
	Question *QuestionEvent `protobuf:"bytes,10,opt,name=question,proto3,oneof"`
}

type Event_Chat struct {
	Chat *ChatEvent `protobuf:"bytes,13,opt,name=chat,proto3,oneof"`
}

func (*Event_Question) isEvent_Detail() {}

func (*Event_Chat) isEvent_Detail() {}

type QuestionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	IsCorrect     bool                   `protobuf:"varint,2,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // 错题才有
	UserAnswer    string                 `protobuf:"bytes,4,opt,name=user_answer,json=userAnswer,proto3" json:"user_answer,omitempty"`
	RightAnswer   string                 `protobuf:"bytes,5,opt,name=right_answer,json=rightAnswer,proto3" json:"right_answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionEvent) Reset() {
	*x = QuestionEvent{}
	mi := &file_memorypb_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionEvent) ProtoMessage() {}

func (x *QuestionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_memorypb_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionEvent.ProtoReflect.Descriptor instead.
func (*QuestionEvent) Descriptor() ([]byte, []int) {
	return file_memorypb_memory_proto_rawDescGZIP(), []int{1}
}

func (x *QuestionEvent) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *QuestionEvent) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *QuestionEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *QuestionEvent) GetUserAnswer() string {
	if x != nil {
		return x.UserAnswer
	}
	return ""
}

func (x *QuestionEvent) GetRightAnswer() string {
	if x != nil {
		return x.RightAnswer
	}
	return ""
}

type ChatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Intent        string                 `protobuf:"bytes,2,opt,name=intent,proto3" json:"intent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_memorypb_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_memorypb_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_memorypb_memory_proto_rawDescGZIP(), []int{2}
}

func (x *ChatEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatEvent) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

// 写入短期记忆
type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_memorypb_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memorypb_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_memorypb_memory_proto_rawDescGZIP(), []int{3}
}

func (x *WriteRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_memorypb_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memorypb_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_memorypb_memory_proto_rawDescGZIP(), []int{4}
}

func (x *WriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_memorypb_memory_proto protoreflect.FileDescriptor

const file_memorypb_memory_proto_rawDesc = "" +
	"\n" +
	"\x15memorypb/memory.proto\x12\x06memory\"\xad\x02\n" +
	"\x05Event\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12!\n" +
	"\fknowledge_id\x18\x02 \x01(\tR\vknowledgeId\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\tR\avideoId\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x04 \x01(\tR\tsegmentId\x12\x0e\n" +
	"\x02ts\x18\x05 \x01(\x03R\x02ts\x120\n" +
	"\n" +
	"event_type\x18\x06 \x01(\x0e2\x11.memory.EventTypeR\teventType\x123\n" +
	"\bquestion\x18\n" +
	" \x01(\v2\x15.memory.QuestionEventH\x00R\bquestion\x12'\n" +
	"\x04chat\x18\r \x01(\v2\x11.memory.ChatEventH\x00R\x04chatB\b\n" +
	"\x06detail\"\xad\x01\n" +
	"\rQuestionEvent\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x02 \x01(\bR\tisCorrect\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\vuser_answer\x18\x04 \x01(\tR\n" +
	"userAnswer\x12!\n" +
	"\fright_answer\x18\x05 \x01(\tR\vrightAnswer\"7\n" +
	"\tChatEvent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06intent\x18\x02 \x01(\tR\x06intent\"3\n" +
	"\fWriteRequest\x12#\n" +
	"\x05event\x18\x01 \x01(\v2\r.memory.EventR\x05event\")\n" +
	"\rWriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*:\n" +
	"\tEventType\x12\f\n" +
	"\bQUESTION\x10\x00\x12\t\n" +
	"\x05PAUSE\x10\x01\x12\n" +
	"\n" +
	"\x06REPLAY\x10\x02\x12\b\n" +
	"\x04CHAT\x10\x032E\n" +
	"\rMemoryService\x124\n" +
	"\x05Write\x12\x14.memory.WriteRequest\x1a\x15.memory.WriteResponseB?Z=github.com/Knowpals/Knowpals-be-go/api/grpc/memorypb;memorypbb\x06proto3"

var (
	file_memorypb_memory_proto_rawDescOnce sync.Once
	file_memorypb_memory_proto_rawDescData []byte
)

func file_memorypb_memory_proto_rawDescGZIP() []byte {
	file_memorypb_memory_proto_rawDescOnce.Do(func() {
		file_memorypb_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memorypb_memory_proto_rawDesc), len(file_memorypb_memory_proto_rawDesc)))
	})
	return file_memorypb_memory_proto_rawDescData
}

var file_memorypb_memory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_memorypb_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_memorypb_memory_proto_goTypes = []any{
	(EventType)(0),        // 0: memory.EventType
	(*Event)(nil),         // 1: memory.Event
	(*QuestionEvent)(nil), // 2: memory.QuestionEvent
	(*ChatEvent)(nil),     // 3: memory.ChatEvent
	(*WriteRequest)(nil),  // 4: memory.WriteRequest
	(*WriteResponse)(nil), // 5: memory.WriteResponse
}
var file_memorypb_memory_proto_depIdxs = []int32{
	0, // 0: memory.Event.event_type:type_name -> memory.EventType
	2, // 1: memory.Event.question:type_name -> memory.QuestionEvent
	3, // 2: memory.Event.chat:type_name -> memory.ChatEvent
	1, // 3: memory.WriteRequest.event:type_name -> memory.Event
	4, // 4: memory.MemoryService.Write:input_type -> memory.WriteRequest
	5, // 5: memory.MemoryService.Write:output_type -> memory.WriteResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_memorypb_memory_proto_init() }
func file_memorypb_memory_proto_init() {
	if File_memorypb_memory_proto != nil {
		return
	}
	file_memorypb_memory_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_Question)(nil),
		(*Event_Chat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memorypb_memory_proto_rawDesc), len(file_memorypb_memory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_memorypb_memory_proto_goTypes,
		DependencyIndexes: file_memorypb_memory_proto_depIdxs,
		EnumInfos:         file_memorypb_memory_proto_enumTypes,
		MessageInfos:      file_memorypb_memory_proto_msgTypes,
	}.Build()
	File_memorypb_memory_proto = out.File
	file_memorypb_memory_proto_goTypes = nil
	file_memorypb_memory_proto_depIdxs = nil
}
