// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/behavior/class-progress/{class_id}/{status}": {
            "get": {
                "description": "获取学生在某个班级下的视频学习情况",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "behavior"
                ],
                "summary": "获取班级内视频的观看进度",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "班级ID",
                        "name": "class_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "all",
                            "finished",
                            "todo",
                            "expired"
                        ],
                        "type": "string",
                        "description": "视频状态",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/behavior.GetClassVideoProgressResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/behavior/record": {
            "post": {
                "description": "记录暂停、回放、播放等行为及时长",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "behavior"
                ],
                "summary": "记录学生视频观看行为",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "行为上报参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/behavior.RecordActionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/behavior/update-progress": {
            "post": {
                "description": "上报当前播放秒数，更新最大进度与完成状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "behavior"
                ],
                "summary": "更新学生视频观看进度",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "进度参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/behavior.UpdateProgressReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/class/create": {
            "post": {
                "description": "教师创建班级，返回班级信息和邀请码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "class"
                ],
                "summary": "教师创建班级",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建班级参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/class.CreateClassRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/class.CreateClassResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/class/info/{class_id}": {
            "get": {
                "description": "获取班级基本信息，单参数使用 path",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "class"
                ],
                "summary": "获取班级详情",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "班级ID",
                        "name": "class_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/class.GetClassInfoResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/class/join": {
            "post": {
                "description": "学生使用邀请码加入班级",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "class"
                ],
                "summary": "学生加入班级",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "邀请码",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/class.JoinClassRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/class/my-created": {
            "get": {
                "description": "获取当前老师创建的所有班级",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "class"
                ],
                "summary": "获取教师创建的班级列表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/class.GetMyCreatedClassesResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/class/my-joined": {
            "get": {
                "description": "获取当前学生加入的所有班级",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "class"
                ],
                "summary": "获取学生加入的班级列表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/class.GetMyJoinedClassesResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/class/quit/{class_id}": {
            "post": {
                "description": "学生退出指定班级，单参数使用 path",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "class"
                ],
                "summary": "学生退出班级",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "班级ID",
                        "name": "class_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/class/students/{class_id}": {
            "get": {
                "description": "获取指定班级的所有学生，单参数使用 path",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "class"
                ],
                "summary": "获取班级内学生列表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "班级ID",
                        "name": "class_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/class.GetClassStudentsResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/question/answer": {
            "post": {
                "description": "学生提交单个视频/片段内的题目答案，系统自动批改并返回结果",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "学生批量提交答题答案",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "学生答题参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/question.AnswerQuestionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/question.AnswerQuestionResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/question/generate/{video_id}": {
            "get": {
                "description": "根据视频ID自动生成课后练习题，供教师确认后发布",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "AI生成视频课后习题",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "视频ID参数",
                        "name": "video_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/question.GenerateVideoExerciseResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/stat/class": {
            "get": {
                "description": "获取班级在某个视频下的整体数据：正确率、完成率、薄弱知识点、高频暂停/回放片段",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistic"
                ],
                "summary": "获取班级整体学情统计",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "获取班级情况参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/statistic.GetClassStatReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/statistic.GetClassStatResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/stat/student/overview": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistic"
                ],
                "summary": "获取学生总体学习统计",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/statistic.GetStudentOverviewResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/stat/student/{video_id}": {
            "get": {
                "description": "获取学生单个视频的答题正确率、观看时长、暂停次数、薄弱知识点",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistic"
                ],
                "summary": "获取学生个人学情统计",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "视频ID",
                        "name": "video_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/statistic.GetStudentStatResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/forgotPassword": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "忘记密码",
                "parameters": [
                    {
                        "description": "重置密码参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ForgotPasswordReq"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/user/getUser/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "根据id查询用户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/user/loginByCode": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户验证码登录",
                "parameters": [
                    {
                        "description": "登陆参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.LoginByVerifyCode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/user.LoginResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user/loginByPassword": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户密码登录",
                "parameters": [
                    {
                        "description": "登陆参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.LoginByPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/user.LoginResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/user.RegisterResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user/sendCode": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "发送验证码",
                "parameters": [
                    {
                        "description": "注册参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.SendCodeRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/video/getDetail/{video_id}": {
            "get": {
                "description": "获取视频详情、分段、视频内题目、课后习题",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "获取视频详情（分段+题目）",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "视频id",
                        "name": "video_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/video.GetVideoDetailResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/video/getTasks/{class_id}": {
            "get": {
                "description": "老师获取班级的所有视频任务",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "获取班级视频任务列表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "班级id",
                        "name": "class_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/video.GetClassVideosResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/video/my-uploaded": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "获取老师上传的视频列表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/video.GetMyUploadedVideosResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/video/post-to-class": {
            "post": {
                "description": "老师将视频作为任务下发给多个班级",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "下发视频任务到班级",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/video.PostVideoToClassReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/video/task/process": {
            "post": {
                "description": "获取视频任务发送进度",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "获取视频任务发送进度",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/video.GetTaskUploadingProcessReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/video.GetTaskUploadingProcessResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/video/upload": {
            "post": {
                "description": "教师上传教学视频，支持 mp4 格式，form-data 提交",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "上传视频文件",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer 认证令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "视频标题",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "视频文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "截止日期 格式：2025-12-31 23:59:59",
                        "name": "deadline",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/video.UploadVideoResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/http.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "behavior.GetClassVideoProgressResp": {
            "type": "object",
            "properties": {
                "progress_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/behavior.VideoProgress"
                    }
                }
            }
        },
        "behavior.RecordActionReq": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer"
                },
                "event": {
                    "description": "pause|replay",
                    "type": "string"
                },
                "segment_id": {
                    "type": "integer"
                },
                "video_id": {
                    "type": "integer"
                }
            }
        },
        "behavior.UpdateProgressReq": {
            "type": "object",
            "properties": {
                "current_sec": {
                    "type": "integer"
                },
                "video_id": {
                    "type": "integer"
                }
            }
        },
        "behavior.VideoProgress": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deadline": {
                    "type": "string"
                },
                "progress_percent": {
                    "description": "完成进度百分比",
                    "type": "integer"
                },
                "status": {
                    "description": "finished | todo | expired",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "video_id": {
                    "type": "integer"
                },
                "watch_time": {
                    "description": "总观看时长",
                    "type": "integer"
                }
            }
        },
        "class.ClassInfo": {
            "type": "object",
            "properties": {
                "class_id": {
                    "type": "integer"
                },
                "class_name": {
                    "type": "string"
                },
                "invite_code": {
                    "type": "string"
                },
                "teacher_id": {
                    "type": "integer"
                },
                "teacher_name": {
                    "type": "string"
                }
            }
        },
        "class.CreateClassRequest": {
            "type": "object",
            "required": [
                "class_name"
            ],
            "properties": {
                "class_name": {
                    "type": "string"
                }
            }
        },
        "class.CreateClassResp": {
            "type": "object",
            "properties": {
                "class_id": {
                    "type": "integer"
                },
                "class_name": {
                    "type": "string"
                },
                "invite_code": {
                    "type": "string"
                }
            }
        },
        "class.GetClassInfoResp": {
            "type": "object",
            "properties": {
                "class_info": {
                    "$ref": "#/definitions/class.ClassInfo"
                }
            }
        },
        "class.GetClassStudentsResp": {
            "type": "object",
            "properties": {
                "students": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/class.Student"
                    }
                }
            }
        },
        "class.GetMyCreatedClassesResp": {
            "type": "object",
            "properties": {
                "class_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/class.ClassInfo"
                    }
                }
            }
        },
        "class.GetMyJoinedClassesResp": {
            "type": "object",
            "properties": {
                "class_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/class.ClassInfo"
                    }
                }
            }
        },
        "class.JoinClassRequest": {
            "type": "object",
            "required": [
                "invite_code"
            ],
            "properties": {
                "invite_code": {
                    "type": "string"
                }
            }
        },
        "class.Student": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "http.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "question.AnswerQuestionReq": {
            "type": "object",
            "properties": {
                "studentanswers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/question.StudentAnswer"
                    }
                },
                "video_id": {
                    "type": "integer"
                }
            }
        },
        "question.AnswerQuestionResp": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/question.Result"
                    }
                }
            }
        },
        "question.GenerateVideoExerciseResp": {
            "type": "object",
            "properties": {
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/question.Question"
                    }
                }
            }
        },
        "question.KnowledgePoint": {
            "type": "object",
            "properties": {
                "knowledge_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "question.Question": {
            "type": "object",
            "properties": {
                "analysis": {
                    "type": "string"
                },
                "answer": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "knowledge_points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/question.KnowledgePoint"
                    }
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "segment_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "question.Result": {
            "type": "object",
            "properties": {
                "analysis": {
                    "type": "string"
                },
                "answer": {
                    "type": "string"
                },
                "is_correct": {
                    "type": "boolean"
                },
                "question_id": {
                    "type": "integer"
                }
            }
        },
        "question.StudentAnswer": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "question_id": {
                    "type": "integer"
                },
                "time_cost": {
                    "type": "integer"
                }
            }
        },
        "statistic.AverageKnowledgePoint": {
            "type": "object",
            "properties": {
                "average_master_score": {
                    "type": "number"
                },
                "knowledge_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "weak_rate": {
                    "description": "低于平均掌握程度分数的比例",
                    "type": "number"
                }
            }
        },
        "statistic.GetClassStatReq": {
            "type": "object",
            "properties": {
                "class_id": {
                    "type": "integer"
                },
                "video_id": {
                    "type": "integer"
                }
            }
        },
        "statistic.GetClassStatResp": {
            "type": "object",
            "properties": {
                "overview": {
                    "$ref": "#/definitions/statistic.Overview"
                },
                "top_pause_action": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/statistic.PauseAction"
                    }
                },
                "top_questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/statistic.QuestionStat"
                    }
                },
                "top_replay_action": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/statistic.ReplayAction"
                    }
                },
                "weak_knowledge_point": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/statistic.AverageKnowledgePoint"
                    }
                }
            }
        },
        "statistic.GetStudentOverviewResp": {
            "type": "object",
            "properties": {
                "correct_rate": {
                    "type": "number"
                },
                "finished_count": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                },
                "total_watch_time_sec": {
                    "type": "integer"
                }
            }
        },
        "statistic.GetStudentStatResp": {
            "type": "object",
            "properties": {
                "correct_rate": {
                    "description": "题目正确率",
                    "type": "number"
                },
                "knowledge_points": {
                    "description": "薄弱知识点（薄弱知识点得分，要提前确定一个阈值）",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/statistic.KnowledgePoint"
                    }
                },
                "pause_count": {
                    "description": "暂停总次数",
                    "type": "integer"
                },
                "replay_count": {
                    "description": "回看总次数",
                    "type": "integer"
                },
                "status": {
                    "description": "任务完成情况：finished | todo | expired",
                    "type": "string"
                },
                "time_cost": {
                    "description": "视频观看时长",
                    "type": "integer"
                },
                "top_pause_action": {
                    "description": "暂停次数最高的片段（TopN）",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/statistic.PauseAction"
                    }
                },
                "top_replay_action": {
                    "description": "回放次数最高的片段（TopN）",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/statistic.ReplayAction"
                    }
                }
            }
        },
        "statistic.KnowledgePoint": {
            "type": "object",
            "properties": {
                "knowledge_id": {
                    "type": "integer"
                },
                "master_score": {
                    "type": "number"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "statistic.Overview": {
            "type": "object",
            "properties": {
                "average_correct_rate": {
                    "description": "平均答题正确率",
                    "type": "number"
                },
                "average_time_cost": {
                    "description": "平均观看时长",
                    "type": "integer"
                },
                "complete_rate": {
                    "description": "任务完成率",
                    "type": "number"
                },
                "total_pause_count": {
                    "description": "总暂停时长",
                    "type": "integer"
                }
            }
        },
        "statistic.PauseAction": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "integer"
                },
                "pause_count": {
                    "type": "integer"
                },
                "segment_id": {
                    "type": "integer"
                },
                "start": {
                    "type": "integer"
                }
            }
        },
        "statistic.QuestionStat": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "error_rate": {
                    "type": "number"
                },
                "question_id": {
                    "type": "integer"
                }
            }
        },
        "statistic.ReplayAction": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "integer"
                },
                "replay_count": {
                    "type": "integer"
                },
                "segment_id": {
                    "type": "integer"
                },
                "start": {
                    "type": "integer"
                }
            }
        },
        "user.ForgotPasswordReq": {
            "type": "object",
            "required": [
                "email",
                "new_password",
                "verify_code"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string"
                },
                "verify_code": {
                    "type": "string"
                }
            }
        },
        "user.LoginByPassword": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "user.LoginByVerifyCode": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "verify_code": {
                    "type": "string"
                }
            }
        },
        "user.LoginResp": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "user.RegisterRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.RegisterResp": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "user.SendCodeRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "video.GetClassVideosResp": {
            "type": "object",
            "properties": {
                "video_tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/video.VideoTask"
                    }
                }
            }
        },
        "video.GetMyUploadedVideosResp": {
            "type": "object",
            "properties": {
                "videos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/video.VideoTask"
                    }
                }
            }
        },
        "video.GetTaskUploadingProcessReq": {
            "type": "object",
            "required": [
                "jobID"
            ],
            "properties": {
                "jobID": {
                    "type": "string"
                }
            }
        },
        "video.GetTaskUploadingProcessResp": {
            "type": "object",
            "properties": {
                "job_id": {
                    "type": "string"
                },
                "stage": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "video.GetVideoDetailResp": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer"
                },
                "knowledge": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/video.KnowledgePointResp"
                    }
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/question.Question"
                    }
                },
                "segments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/video.Segment"
                    }
                },
                "title": {
                    "type": "string"
                },
                "video_id": {
                    "type": "integer"
                }
            }
        },
        "video.KnowledgePointResp": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "knowledge_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "video.PostVideoToClassReq": {
            "type": "object",
            "properties": {
                "class_list": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "video_id": {
                    "type": "integer"
                }
            }
        },
        "video.Segment": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "question": {
                    "$ref": "#/definitions/question.Question"
                },
                "segment_id": {
                    "type": "string"
                },
                "start": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "video.UploadVideoResp": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer"
                },
                "job_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "video_id": {
                    "type": "integer"
                }
            }
        },
        "video.VideoTask": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deadline": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "video_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
